content:
  content1:
    date: "2005"
    head: "Founded"
    body: "The club was founded in the year of 2005"
  content2:
    date: "2007"
    head: "Official Recognition"
    body: "The club got official recognition in the year of 2007"
  content3:
    date: "2017-2018"
    head: "GSoC"
    body: "Highest Number Of Google Summer of Code interns from Odisha in 2017 and 2018"
  content4:
    date: "2018"
    head: "Outreachy"
    body: "First Outreachy intern of CET"
  content5:
    date: "2018"
    head: "Smart Odisha Hackathon"
    body: "4 winning teams from various sectors, from Zairza" 
